version: '3.8'

services:
  project-management-app-mysql:
    image: mysql:8.0.32
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3307
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}

  project-management-app-next-js:
    build: ./next-js
    ports:
      - "5122:3000"
    container_name: project-management-app-next-js-container_name
    volumes:
      - ./next-js:/app/next-js
      - /app/next-js/node_modules
    depends_on:
      - project-management-app-mysql
    stdin_open: true
    tty: true
